apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-node
  namespace: interconnect
spec:
  type: NodePort
  ports:
  - name: client-np
    port: 2379
    nodePort: 30379
    protocol: TCP
    targetPort: 2379
  - name: peer-np
    port: 2380
    nodePort: 30380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd